/*Attempt at removing duplicates after all necessary columns have been changed to matching values. */

CREATE TABLE vmerge(
ID INT NOT NULL AUTO_INCREMENT,
FName varchar(50),
MName varchar(50),
LName varchar(100) not null,
Suffix varchar(5),
DOB varchar(25),
DOD varchar(25),
CName varchar(100),
CSection varchar(25),
CRow varchar(25),
MarkerPicLoc varchar(250),
MarkerLocation varchar(10),
MiscPicLoc varchar(250),
Branch1 varchar(100),
Rank1 varchar(100),
Branch2 varchar(100),
Rank2 varchar(100),
Conflict1 varchar(100),
Conflict2 varchar(100),
Conflict3 varchar(100),
Awards varchar (150),
MilPicLoc varchar(250),
Comments varchar(750),
UnitShip varchar(250),
Primary Key(ID));


INSERT INTO vmerge (FName, MName, LName, Suffix, DOB, DOD, CName, CSection, CRow, MarkerPicLoc, MarkerLocation,
 MiscPicLoc, Branch1, Rank1, Branch2, Rank2, Conflict1, Conflict2, Conflict3, UnitShip, Awards, MilPicLoc, Comments)
SELECT DISTINCT
	FNAME, MNAME, LNAME, SUFFIX, DOB, DOD, CEMETERY, SECTION, ROW, `MARKER PHOTO`, `MARKER LOCATION`, `MISC PHOTO`, BRANCH1, RANK1, BRANCH2, RANK2, CONFLICT1, CONFLICT2, CONFLICT3, `UNIT/SHIP`, `AWARDS/ DECORATIONS`, `MILITARY PHOTO`, `REMARKS/ COMMENTS`
FROM(
SELECT
	FNAME, MNAME, LNAME, SUFFIX, DOB, DOD, CEMETERY, SECTION, ROW, `MARKER PHOTO`, `MARKER LOCATION`, `MISC PHOTO`, BRANCH1, RANK1, BRANCH2, RANK2, CONFLICT1, CONFLICT2, CONFLICT3, `UNIT/SHIP`, `AWARDS/ DECORATIONS`, `MILITARY PHOTO`, `REMARKS/ COMMENTS`
FROM
	db1
UNION	
SELECT
	FNAME, MNAME, LNAME, SUFFIX, DOB, DOD, CEMETERY, SECTION, ROW, `MARKER PHOTO`, `MARKER LOCATION`, `MISC PHOTO`, BRANCH1, RANK1, BRANCH2, RANK2, CONFLICT1, CONFLICT2, CONFLICT3, `UNIT/SHIP`, `AWARDS/ DECORATIONS`, `MILITARY PHOTO`, `REMARKS/ COMMENTS`
FROM
	db2
UNION	
SELECT
	FNAME, MNAME, LNAME, SUFFIX, DOB, DOD, CEMETERY, SECTION, ROW, `MARKER PHOTO`, `MARKER LOCATION`, `MISC PHOTO`, BRANCH1, RANK1, BRANCH2, RANK2, CONFLICT1, CONFLICT2, CONFLICT3, `UNIT/SHIP`, `AWARDS/ DECORATIONS`, `MILITARY PHOTO`, `REMARKS/ COMMENTS`
FROM
	db3
UNION
SELECT
	FNAME, MNAME, LNAME, SUFFIX, DOB, DOD, CEMETERY, SECTION, ROW, `MARKER PHOTO`, `MARKER LOCATION`, `MISC PHOTO`, BRANCH1, RANK1, BRANCH2, RANK2, CONFLICT1, CONFLICT2, CONFLICT3, `UNIT/SHIP`, `AWARDS/ DECORATIONS`, `MILITARY PHOTO`, `REMARKS/ COMMENTS`
FROM
	db4
UNION
SELECT
	FNAME, MNAME, LNAME, SUFFIX, DOB, DOD, CEMETERY, SECTION, ROW, `MARKER PHOTO`, `MARKER LOCATION`, `MISC PHOTO`, BRANCH1, RANK1, BRANCH2, RANK2, CONFLICT1, CONFLICT2, CONFLICT3, `UNIT/SHIP`, `AWARDS/ DECORATIONS`, `MILITARY PHOTO`, `REMARKS/ COMMENTS`
FROM
	db5
UNION
SELECT
	FNAME, MNAME, LNAME, SUFFIX, DOB, DOD, CEMETERY, SECTION, ROW, `MARKER PHOTO`, `MARKER LOCATION`, `MISC PHOTO`, BRANCH1, RANK1, BRANCH2, RANK2, CONFLICT1, CONFLICT2, CONFLICT3, `UNIT/SHIP`, `AWARDS/ DECORATIONS`, `MILITARY PHOTO`, `REMARKS/ COMMENTS`
FROM
	db6) V;

/*
ALTER TABLE vmerge ADD COLUMN dobdate date AFTER DOB;
ALTER TABLE vmerge ADD COLUMN doddate date AFTER DOD;
UPDATE vmerge SET dobdate = str_to_date(DOB, '%m/%d/%Y');
UPDATE vmerge SET doddate = str_to_date(DOD, '%m/%d/%Y');
*/