INSERT INTO BranchesList (BranchName) VALUES ('AL NATIONAL GUARD');
INSERT INTO BranchesList (BranchName) VALUES ('CSA');
INSERT INTO BranchesList (BranchName) VALUES ('ROYAL CANADIAN AIR FORCE');
INSERT INTO BranchesList (BranchName, BranchPicLoc) VALUES ('US AIR FORCE', 'US Air Force.jpg');
INSERT INTO BranchesList (BranchName) VALUES ('US AIR FORCE RESERVE');
INSERT INTO BranchesList (BranchName, BranchPicLoc) VALUES ('US ARMY', 'US Army.jpg');
INSERT INTO BranchesList (BranchName) VALUES ('US ARMY AIR CORPS');
INSERT INTO BranchesList (BranchName) VALUES ('US ARMY RESERVE');
INSERT INTO BranchesList (BranchName, BranchPicLoc) VALUES ('US COAST GUARD', 'US Coast Guard.jpg');
INSERT INTO BranchesList (BranchName) VALUES ('US COAST GUARD RESERVE');
INSERT INTO BranchesList (BranchName, BranchPicLoc) VALUES ('US MARINE CORPS', 'USMC.jpg');
INSERT INTO BranchesList (BranchName) VALUES ('US MARINE CORPS RESERVE');
INSERT INTO BranchesList (BranchName) VALUES ('US MERCHANT MARINES');
INSERT INTO BranchesList (BranchName) VALUES ('US NAVAL RESERVE');
INSERT INTO BranchesList (BranchName, BranchPicLoc) VALUES ('US NAVY','US Navy.jpg');
INSERT INTO BranchesList (BranchName) VALUES('US ARMY AIR FORCE');
INSERT INTO BranchesList (BranchName) VALUES('US NATIONAL GUARD');
INSERT INTO BranchesList (BranchName) VALUES('UNITED STATES OF AMERICA (UNION)');
INSERT INTO BranchesList (BranchName) VALUES('UNKNOWN');