Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Adams 1','Adams Cemetery, Lester, AL 35647','Lester');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Anderson 2','Anderson Cemetery, Madison, AL 35756','Madison');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Antioch 1','Antioch Cemetery Number One, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Antioch 2','Antioch Cemetery, 18483 Morris Rd, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Arlington National Cemetery','Arlington National Cemetery, Arlington, VA 22211','Arlington');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Athens City','Athens City Cemetery, 576-, 598 Washington St E, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Atkinson-Harlow','Spence Cave Road Limestone County, Alabama, USA','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Bailes','Bailes Cemetery, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Barker','Barker Cemetery, Alabama 35614','Rogersville');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Berea','Berea Cemetery, Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Bethel','Bethel Cemetery, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Bethlehem','Bethlehem Cemetery, Russellville, AL 35654','Russellville');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Bibb','Bibb Cemetery, Tanner, AL 35671','Tanner');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Blackwell-Collier','Blackwell-Collier Cemetery, 4147-4237 SW Bilow Rd, Madison, AL 35756','Madison');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Bottom','Bottom Cemetery, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Cambridge Church Cemetery','Cambridge Church Cemetery, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Collier 1','Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Collier 2','Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Copeland','Copeland Rd & Wells Rd, Alabama 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Cox 1','Cox Cemetery, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Cummings Cemetery','Cummins Cemetery, Toney, AL 35773','Toney');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Cunningham','Cunningham Cemetery, Lester, AL 35647','Lester');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Delap Cemetery','Limestone County, Alabama, USA','Ardmore');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Dement','Dement Cemetery, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Dupree','Dupree Cemetery, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Elk View Memorial Cemetery','Athens, Limestone County, Alabama, USA','Cairo');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Evans 1','Evans Cemetery, Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Evans 2','','Pike County');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Fairview Baptist cemetery','Fairview Baptist Church, 27550 Nick Davis Rd, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Faulkner','Limestone County, Alabama, USA','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Fielding','Fielding Cemetery, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Gamble','Gamble Cemetery, Tanner, AL 35671','Tanner');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Gardens of Memory','Gardens of Memory Cemetery, 6200 hwy 431 N, Headland, AL 36345','Headland');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Gatlin','Gatlin Cemetery, Ardmore, AL 35739','Ardmore');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Germantown','Thach, Limestone County, Alabama, USA','Thach');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Gordon','Gordon Cemetery, Gordon, AL 36343','Gordon');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Grigsby','Grigsby Cemetery, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hardy','Hardy Cemetery, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Harris','Harris Cemetery, Akron, AL 35441','Akron');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hasting','Hasting Cemetery, Ardmore, AL 35739','Ardmore');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hatchett 1','Hatchett Cemetery, Tanner, AL 35671','Tanner');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hatchett 2','Hatchett Cemetery, Toney, AL 35773','Toney');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hesters Chapel','Hesters Chapel Cemetery, Lester, AL 35647','Lester');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Higgins','Higgins Cemetery, Alabama','Cairo');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hightower','Hightower Cemetery, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hodges','Hodges Cemetery, Fultondale, AL 35068','Fultondale');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Holt','Limestone County, Alabama, USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Hudson','Calhoun County','Calhoun County');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Huntsville Memorial Gardens','Huntsville Memory Gardens, 6810 University Dr NW, Huntsville, AL 35806','Huntsville');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Isoms Chapel Cemetery','Isom''s Chapel United Methodist, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Johnson 1','Bremen, Cullman County, Alabama, USA','Bremen');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Johnston Cemetery','Limestone County, Alabama, USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Lebanon','13500 Lebanon Rd Elkmont, Limestone County, Alabama, 35620 USA','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('LEGG','Legg Cemetery, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Lentzville','Lentzville Cemetery, Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('LIMESTONE MEMORIAL GARDENS','Limestone Memorial Gardens, 1987 US-31, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Limestone Presbyterian Church Cemetery','15709 Lee Hwy (US Hwy 72) Athens, Limestone County, Alabama, 35611 USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Malone 1','16250 Lindsay Rd Tanner, Limestone County, Alabama, 35671 USA','Tanner');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Martin (Old Shoal Ford Cemetery)','Limestone County, Alabama, USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Massenburg-Henderson','Limestone County, Alabama, USA','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('McClellan','Fort McClellan Military Cemetery, 162 Goode Rd, Anniston, AL 36205','Anniston');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('McCravy','McCravy Cemetery, Anderson, AL 35610','Anderson');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('McCuan-Moss Cemetery','Cairo, Limestone County, Alabama, USA','Cairo');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Menefee','Menefee Cemetery, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Mooresville Cemetery','Mooresville Cemetery, Co Rd 71, Mooresville, AL 35649','Moorseville');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Motes','Motes Cemetery, Ardmore, AL 35739','Ardmore');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Mount Pleasant ','30239-29381 Old Scrouge Rd, Ardmore, AL 35739','Ardmore');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Murphy','Limestone County, Alabama, USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Myers','Myers Cemetery, Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Nebo','Mt Nebo Cemetery, Trussville, AL 35173','Trussville');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('New Garden','New Garden Cemetery, 20350 New Garden Rd, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Newby','Newby Cemetery, Toney, AL 35773','Toney');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Oak Grove','33583 Buck Island Rd Cherry Grove, Limestone County, Alabama, 35610 USA','Anderson');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Old Salem','26300 Salem Minor Hill Rd Salem, Limestone County, Alabama, 35647 USA','Salem');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Peebles','Peebles Cemetery, Madison, AL 35756','Madison');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Pettusville Church Cemetery','Pettusville Church Cemetery, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Piney chapel','Limestone County, Alabama, USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Pleasant Grove','Pleasant Grove Church, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Pleasant Point','Pisgah, Limestone County, Alabama, USA','Pisgah');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Poplar Creek','Poplar Creek Missionary Baptist Church, 16031 Poplar Creek Rd, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Rambo','Rambo Cemetery, Holt Rd, Athens, AL 35613','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Reunion','Thach, Limestone County, Alabama, USA','Thach');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Riddle','imestone County, Alabama, USA','Lawson');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Ripley','Ripley Cemetery, 12144 Friend Rd, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Robinson','Robinson Cemetery, Toney, AL 35773','Toney');
Insert into Cemeteries (CName, CAddress, CCity, CemAirPicLoc, DirectionsPicLoc) VALUES ('Roselawn','Roselawn Cemetery, Athens, AL 35613','Athens','Roselawn.png','RoselawnDirections.jpg');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Round Island Church Cemetery','Round Island Baptist Church, 14790 Brownsferry Rd, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Sandlin','Sandlin Cemetery, Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Shoemaker','Shoemaker Cemetery, Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Smith','Smith Cemetery, AL-127, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Stewart','Stewart Cemetery, Tanner, AL 35671','Tanner');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Sylone','Sylone Cemetery, Elkmont, AL 35620','Elkmont');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Tanner','Tanner Cemetery, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Temperance Oak','Temperance Oak Cemetery, Athens, AL 35614','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Thatch','Union Hill, Limestone County, Alabama, USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Thatch-Mann','Thatch-Mann Cemetery, 1801-, 1803 W Hobbs St, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Tillery','Tillery Cemetery, Ardmore, AL 35739','Ardmore');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Todd','Todd Cemetery, Lester, AL 35647','Lester');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Wallace 1','Wallace Cemetery, Athens, AL 35611','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Wallace 2','Limestone County, Alabama, USA','Athens');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Wesley Chapel Cemetery','Wesley Chapel Cemetery, Harvest, AL 35749','Harvest');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Wid Legg','Limestone County, Alabama, USA','Limestone County');
Insert into Cemeteries (CName, CAddress, CCity) VALUES ('Yarbrough','Yarbrough Cemetery, Athens, AL 35611','Athens');
