INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Airman Basic', 'AB');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Airman','Amn');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Airman First class','A1C');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Senior Airman','SrA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Staff Sergeant','SSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Technical Sergeant','TSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Master Sergeant','MSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Senior Master Sergeant','SMSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Chief Master Sergeant','CMSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Command Chief Master Sergeant','CCM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Chief Master Sergeant of the Air Force','CMSAF');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Second Lieutenant','2d Lt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','First Lieutenant','1st Lt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Captain','Capt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Major','Maj');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Lieutenant Colonel','Lt Col');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Colonel','Col');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Brigadier General','Brig Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Major General','Maj Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Lietenant General','Lt Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','General','Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','General of the Air Force','GAF');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Airman Second Class','A2C');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Airman Third Class','A3C');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','UNKNOWN','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Chief Warrant Officer','CWO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','Sergeant','Sgt');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Private','PV1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Private Second Class','PV2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Private First Class','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Specialist','SPC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Staff Sergeant','SSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Sergeant First Class','SFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Master Sergeant','MSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','First Sergeant','1SG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Sergeant Major','SGM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Command Sergeant Major','CSM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Sergeant Major of the Army','SMA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Warrant Officer 1','WO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Chief Warrant Officer Second Class','CW2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Chief Warrant Officer Third Class','CW3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Chief Warrant Officer Fourth Class','CW4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Chief Warrant Officer Fifth Class','CW5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','First Lieutenant','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Captain','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Lieutenant Colonel','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Brigadier General','BG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Major General','MG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','Lieutenant General','LTG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','General of the Army','GA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','General of the Armies','GAS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','HORSESHOER','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','MESS SERGEANT','MESS SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','SPECIALIST THIRD CLASS','SP3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','SPECIALIST FOURTH CLASS','SP4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','SPECIALIST FIFTH CLASS','SP5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','TECHNICIAN THIRD CLASS','TEC3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','TECHNICIAN FOURTH CLASS','TEC4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','TECHNICIAN FIFTH CLASS','TEC5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','UNKNOWN','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY','TECHNICAL SERGEANT','T/SGT.');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Seaman Recruit','SR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Seaman Apprentice','SA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Seaman','SN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Petty Officer Third Class','PO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Petty Officer Second Class','PO2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Petty Officer First Class','PO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Chief Petty Officer','SCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Master Chief Petty Officer','MCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Command Master Chief Petty Officer','CMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Master Chief Petty Officer Of The Coast Guard','MCPOC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Chief Warrant Officer Second Class','CWO-2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Chief Warrant Officer Third Class','CWO-3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Chief Warrant Officer Fourth Class','CWO-4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Ensign','ENS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Lieutenant Junior Grade','LTJG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Lieutenant','LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Lieutenant Commander','LCDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Commander','CDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Captain','CAPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Rear Admiral Lower Half','RDML');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Rear Admiral','RADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Vice Admiral','VADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','Admiral','ADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Airman','Amn');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Seaman Recruit','SR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Seaman Apprentice','SA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Seaman','SN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Petty Officer Third Class','PO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Petty Officer Second Class','PO2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Petty Officer First Class','PO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Chief Petty Officer','CPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Senior Chief Petty Officer','SCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Master Chief Petty Officer','MCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Command Master Chief Petty Officer','CMDCM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Master Chief Petty Officer Of The Navy','MCPON');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Chief Warrant Officer Second Class','CW2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Chief Warrant Officer Third Class','CW3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Chief Warrant Officer Fourth Class','CW4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Chief Warrant Officer Fifth Class','CW5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Ensign','ENS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Lieutenant Junior Grade','LTJG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Lieutenant','LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Lieutenant Commander','LCDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Commander','CDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Captain','CAPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Rear Admiral Lower Half','RDML');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Rear Admiral','RADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Vice Admiral','VADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Admiral','ADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','Fleet Admiral','FADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION CHIEF MACHINIST''S MATE','ACMM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION MACHINIST''S MATE (JET ENGINE MECHANIC) PETTY OFFICER THIRD CLASS','ADJ3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION STRUCTURAL MECHANIC PETTY OFFICER SECOND CLASS','AM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION STRUCTURAL MECHANIC (SAFETY EQUIPMENT) PETTY OFFICER THIRD CLASS','AME3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION MACHINIST''S MATE FIRST CLASS PETTY OFFICER','AMM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION MACHINIST''S MATE PETTY OFFICER SECOND CLASS','AMM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION MACHINIST''S MATE THIRD CLASS PETTY OFFICER','AMM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION STRUCTURAL MECHANIC (STRUCTURAL) PETTY OFFICER FIRST CLASS','AMS1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION ORDNANCEMAN PETTY OFFICER THIRD CLASS','AO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION FIRE CONTROL TECHNICIAN PETTY OFFICER THIRD CLASS','AQ3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION RADIOMAN PETTY OFFICER SECOND CLASS','ARM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION ELECTRONICS TECHNICIAN PETTY OFFICER FIRST CLASS','AT1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION ELECTRONICS TECHNICIAN CHIEF PETTY OFFICER','ATC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION ELECTRONICS','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','AVIATION CADET','AVCAD');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BAKER FIRST CLASS','BKR1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BAKER THIRD CLASS','BKR3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOATSWAIN''S MATE PETTY OFFICER FIRST CLASS','BM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOATSWAIN''S MATE PETTY OFFICER SECOND CLASS','BM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOATSWAIN''S MATE PETTY OFFICER THIRD CLASS','BM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOATSWAIN''S MATE CHIEF PETTY OFFICER','BMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOATSWAIN''S MATE SEAMAN','BMSN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOILER TECHNICIAN PETTY OFFICER THIRD CLASS','BT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOILER TECHNICIAN CHIEF PETTY OFFICER','BTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','BOILER TECHNICIAN FIREMAN','BTFN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CONSTRUCTION ELECTRICIAN''S MATE (POWER LINE) CONSTRUCTIONMAN APPRENTICE','CECA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CHIEF YEOMAN','CY');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CM1','CM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CM2','CM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CONSTRUCTION MECHANIC (GASOLINE) PETTY OFFICER FIRST CLASS','CMG1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CHIEF MACHINIST''S MATE','CMM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CHIEF MOTOR MACHINIST''S MATE','CMOMM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','COOK','CK');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','COXSWAIN','COX');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','CHIEF RADIO TECHNICIAN','CRT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','COMMISSARYMAN PETTY OFFICER FIRST CLASS','CS1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','COMMISSARYMAN CHIEF PETTY OFFICER','CSC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','COMMUNICATIONS TECHNICIAN PETTY OFFICER THIRD CLASS','CT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','COMMUNICATIONS YEOMAN SEAMAN','CYNSN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','ELECTRICIAN''S MATE PETTY OFFICER SECOND CLASS','EM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','ELECTRONICS TECHNICIAN (COMMUNICATIONS) PETTY OFFICER SECOND CLASS','ETN2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','ELECTRONICS TECHNICIAN PETTY OFFICER SECOND CLASS','ET2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','ELECTRICIAN''S MATE PETTY OFFICER FIRST CLASS (SUBMARINE SERVICE)','EM1(SS)');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','ELECTRICIAN''S MATE PETTY OFFICER FIRST CLASS','EM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','ELECTRICIAN''S MATE PETTY OFFICER THIRD CLASS','EM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','ENGINEMAN PETTY OFFICER SECOND CLASS','EN2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','FIREMAN FIRST CLASS','F1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','FIREMAN SECOND CLASS','F2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','FIREMAN','FN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','PIPEFITTER PETTY OFFICER SECOND CLASS','FP2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','FIREMAN RECRUIT','FR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','GUNNER''S MATE THIRD CLASS PETTY OFFICER','GM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','GUNNER''S MATE (MISSILES) SENIOR CHIEF PETTY OFFICER','GMCS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','GUNNER''S MATE (GUNS) PETTY OFFICER FIRST CLASS','GMG1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','GUNNER''S MATE (GUNS) PETTY OFFICER THIRD CLASS','GMG3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','HOSPITAL CORPSMAN PETTY OFFICER THIRD CLASS','HM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','HULL MAINTENANCE TECHNICIAN SENIOR CHIEF PETTY OFFICER','HTCS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','LANDSMAN','LDS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','METALSMITH FIRST CLASS PETTY OFFICER','M1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MACHINIST''S MATE SECOND CLASS PETTY OFFICER','MM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MACHINIST''S MATE FIRST CLASS PETTY OFFICER (SUBMARINE SERVICE)','MM1(SS)');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MACHINIST''S MATE FIRST CLASS PETTY OFFICER','MM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','METALSMITH PETTY OFFICER THIRD CLASS','ME3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MECHANIC PETTY OFFICER FIRST CLASS','CM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MACHINIST''S MATE THIRD CLASS PETTY OFFICER','MM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MACHINIST''S MATE (GENERAL) CHIEF PETTY OFFICER','MMLC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MOTOR MACHINIST''S MATE THIRD CLASS PETTY OFFICER','MOMM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','MACHINIST''S MATE (SHOP MACHINIST) FIRST CLASS PETTY OFFICER','MMS1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','PHOTOGRAPHER''S MATE AIRMAN','PHAN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','PHOTOGRAPHER''S MATE PETTY OFFICER FIRST CLASS','PH1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','PATTERNMAKER PETTY OFFICER SECOND CLASS','PM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','PAINTER SECOND CLASS PETTY OFFICER','PTR2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','RADIOMAN PETTY OFFICER FIRST CLASS','RM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','RADIOMAN PETTY OFFICER THIRD CLASS','RM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','RADARMAN PETTY OFFICER FIRST CLASS','RD1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','RADARMAN THIRD CLASS PETTY OFFICER','RDM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','RADIOMAN CHIEF PETTY OFFICER','RMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','RADIOMAN SEAMAN','RMSN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SEAMAN FIRST CLASS','S1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SEAMAN SECOND CLASS','S2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SEAMAN SIGNAL COMMUNICATION','SSC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SHIPFITTER THIRD CLASS','SF3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SHIPFITTER (PIPE FITTER) PETTY OFFICER SECOND CLASS','SFP2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SHIP''S SERVICEMAN PETTY OFFICER FIRST CLASS','SH1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SHIP''S SERVICEMAN MASTER CHIEF PETTY OFFICER','SHCM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','STOREKEEPER SECOND CLASS PETTY OFFICER','SK2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SONARMAN PETTY OFFICER FIRST CLASS','SO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SOUNDMAN THIRD CLASS PETTY OFFICER','SOM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','SHIP''S SERVICEMAN (LAUNDRY MAN) SECOND CLASS PETTY OFFICER','SSML2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','TELEMAN (MAILMAN) PETTY OFFICER SECOND CLASS','TEM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','TORPEDOMAN''S MATE PETTY OFFICER THIRD CLASS','TM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','TORPEDOMAN''S MATE PETTY OFFICER FIRST CLASS','TM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','WATER TENDER PETTY OFFICER SECOND CLASS','WT2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','WATER TENDER PETTY OFFICER THIRD CLASS','WT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','YEOMAN SECOND CLASS','Y2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','YEOMAN (TYPIST) PETTY OFFICER THIRD CLASS','YNT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','YEOMAN CHIEF PETTY OFFICER','YNC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Private','PVT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Private First Class','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Lance Corporal','LCPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Staff Sergeant','SSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Gunnery Sergeant','GYSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Master Sergeant','MSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','First Sergeant','1stSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Master Gunnery Sergeant','MGYSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Sergeant Major','SGTMAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Sergeant Major of the Marine Corps','SMMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Warrant Officer','WO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Chief Warrant Officer Second Class','CWO2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Chief Warrant Officer Third Class','CWO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Chief Warrant Officer Fourth Class','CWO4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Chief Warrant Officer Fifth Class','CWO5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Second Lieutenant','2ndLT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','First Lieutenant','1stLT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Captain','CAPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Lieutenant Colonel','LTCOL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Brigadier General','BGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Major General','MAJGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Lieutenant General','LTGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','UNKNOWN','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS','Technical Sergeant','TSgt');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Private','PVT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Musician','MUS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','First Sergeant','1SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Ordnance Sergeant','OSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Quartermaster Sergeant','QMSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Sergeant Major','SGM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','First Lieutenant','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Captain','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Lieutenant Colonel','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Aviator(Basic)','Avr(B)');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Aviator(Trained)','Avr(T)');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Master Corporal','MCPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Warrant Officer','WO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Master Warrant Officer','MWO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Chief Warrant Officer','CWO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Officer Cadet','OCDT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Lieutenant','LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Captain','CAPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Lieutenant-Colonel','LCOL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Brigadier-General','BGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Major-General','MGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','Lieutenant-General','(LGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','UNKNOWN','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('ROYAL CANADIAN AIR FORCE','First Lieutenant','1LT');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Private','PV1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Private First Class','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Specialist','SPC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Staff Sergeant','SSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Sergeant First Class','SFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Master Sergeant','MSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','First Sergeant','1SG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Sergeant Major','SGM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Command Sergeant Major','CSM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Sergeant Major of the Army','SMA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Warrant Officer 1','WO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Chief Warrant Officer Second Class','CW2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Chief Warrant Officer Third Class','CW3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Chief Warrant Officer Fourth Class','CW4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Chief Warrant Officer Fifth Class','CW5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','First Lieutenant','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Captain','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Lieutenant Colonel','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Brigadier General','BG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Major General','MG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','Lieutenant General','LTG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','General of the Army','GA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','General of the Armies','GAS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('AL NATIONAL GUARD','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Airman Basic', 'AB');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Airman','Amn');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Airman First class','A1C');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Senior Airman','SrA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Staff Sergeant','SSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Technical Sergeant','TSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Master Sergeant','MSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Senior Master Sergeant','SMSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Chief Master Sergeant','CMSgt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Command Chief Master Sergeant','CCM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Chief Master Sergeant of the Air Force','CMSAF');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Second Lieutenant','2d Lt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','First Lieutenant','1st Lt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Captain','Capt');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Major','Maj');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Lieutenant Colonel','Lt Col');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Colonel','Col');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Brigadier General','Brig Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Major General','Maj Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Lietenant General','Lt Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','General','Gen');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','General of the Air Force','GAF');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Airman Second Class','A2C');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','Airman Third Class','A3C');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE RESERVE','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Private','PV1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Private Second Class','PV2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Private First Class','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Specialist','SPC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Staff Sergeant','SSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Sergeant First Class','SFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Master Sergeant','MSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','First Sergeant','1SG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Sergeant Major','SGM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Command Sergeant Major','CSM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Sergeant Major of the Army','SMA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Warrant Officer 1','WO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Chief Warrant Officer Second Class','CW2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Chief Warrant Officer Third Class','CW3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Chief Warrant Officer Fourth Class','CW4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Chief Warrant Officer Fifth Class','CW5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','First Lieutenant','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Captain','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Lieutenant Colonel','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Brigadier General','BG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Major General','MG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','Lieutenant General','LTG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','General of the Army','GA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','General of the Armies','GAS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','HORSESHOER','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','MESS SERGEANT','MESS SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','SPECIALIST THIRD CLASS','SP3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','SPECIALIST FOURTH CLASS','SP4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','SPECIALIST FIFTH CLASS','SP5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','TECHNICIAN THIRD CLASS','TEC3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','TECHNICIAN FOURTH CLASS','TEC4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','TECHNICIAN FIFTH CLASS','TEC5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY RESERVE','UNKNOWN','N/A');


INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Seaman Recruit','SR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Seaman Apprentice','SA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Seaman','SN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Petty Officer Third Class','PO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Petty Officer Second Class','PO2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Petty Officer First Class','PO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Chief Petty Officer','SCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Master Chief Petty Officer','MCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Command Master Chief Petty Officer','CMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Master Chief Petty Officer Of The Coast Guard','MCPOC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Chief Warrant Officer Second Class','CWO-2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Chief Warrant Officer Third Class','CWO-3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Chief Warrant Officer Fourth Class','CWO-4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Ensign','ENS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Lieutenant Junior Grade','LTJG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Lieutenant','LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Lieutenant Commander','LCDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Commander','CDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Captain','CAPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Rear Admiral Lower Half','RDML');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Rear Admiral','RADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Vice Admiral','VADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','Admiral','ADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US COAST GUARD RESERVE','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Private','PVT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Private First Class','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Lance Corporal','LCPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Staff Sergeant','SSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Gunnery Sergeant','GYSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Master Sergeant','MSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','First Sergeant','1stSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Master Gunnery Sergeant','MGYSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Sergeant Major','SGTMAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Sergeant Major of the Marine Corps','SMMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Warrant Officer','WO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Chief Warrant Officer Second Class','CWO2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Chief Warrant Officer Third Class','CWO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Chief Warrant Officer Fourth Class','CWO4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Chief Warrant Officer Fifth Class','CWO5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Second Lieutenant','2ndLT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','First Lieutenant','1stLT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Captain','CAPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Lieutenant Colonel','LTCOL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Brigadier General','BGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Major General','MAJGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','Lieutenant General','LTGEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MARINE CORPS RESERVE','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Seaman Recruit','SR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Seaman Apprentice','SA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Seaman','SN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Petty Officer Third Class','PO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Petty Officer Second Class','PO2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Petty Officer First Class','PO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Chief Petty Officer','CPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Senior Chief Petty Officer','SCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Master Chief Petty Officer','MCPO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Command Master Chief Petty Officer','CMDCM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Master Chief Petty Officer Of The Navy','MCPON');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Chief Warrant Officer Second Class','CW2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Chief Warrant Officer Third Class','CW3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Chief Warrant Officer Fourth Class','CW4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Chief Warrant Officer Fifth Class','CW5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Ensign','ENS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Lieutenant Junior Grade','LTJG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Lieutenant','LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Lieutenant Commander','LCDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Commander','CDR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Captain','CAPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Rear Admiral Lower Half','RDML');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Rear Admiral','RADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Vice Admiral','VADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Admiral','ADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','Fleet Admiral','FADM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION CHIEF MACHINIST''S MATE','ACMM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION MACHINIST''S MATE (JET ENGINE MECHANIC) PETTY OFFICER THIRD CLASS','ADJ3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION STRUCTURAL MECHANIC PETTY OFFICER SECOND CLASS','AM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION STRUCTURAL MECHANIC (SAFETY EQUIPMENT) PETTY OFFICER THIRD CLASS','AME3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION MACHINIST''S MATE FIRST CLASS PETTY OFFICER','AMM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION MACHINIST''S MATE PETTY OFFICER SECOND CLASS','AMM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION MACHINIST''S MATE THIRD CLASS PETTY OFFICER','AMM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION STRUCTURAL MECHANIC (STRUCTURAL) PETTY OFFICER FIRST CLASS','AMS1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION ORDNANCEMAN PETTY OFFICER THIRD CLASS','AO3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION FIRE CONTROL TECHNICIAN PETTY OFFICER THIRD CLASS','AQ3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION RADIOMAN PETTY OFFICER SECOND CLASS','ARM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION ELECTRONICS TECHNICIAN PETTY OFFICER FIRST CLASS','AT1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION ELECTRONICS TECHNICIAN CHIEF PETTY OFFICER','ATC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION ELECTRONICS...','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','AVIATION CADET','AVCAD');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BAKER FIRST CLASS','BKR1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BAKER THIRD CLASS','BKR3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOATSWAIN''S MATE PETTY OFFICER FIRST CLASS','BM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOATSWAIN''S MATE PETTY OFFICER SECOND CLASS','BM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOATSWAIN''S MATE PETTY OFFICER THIRD CLASS','BM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOATSWAIN''S MATE CHIEF PETTY OFFICER','BMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOATSWAIN''S MATE SEAMAN','BMSN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOILER TECHNICIAN PETTY OFFICER THIRD CLASS','BT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOILER TECHNICIAN CHIEF PETTY OFFICER','BTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','BOILER TECHNICIAN FIREMAN','BTFN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CONSTRUCTION ELECTRICIAN''S MATE (POWER LINE) CONSTRUCTIONMAN APPRENTICE','CECA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CHIEF YEOMAN','CY');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CM1','CM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CM2','CM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CONSTRUCTION MECHANIC (GASOLINE) PETTY OFFICER FIRST CLASS','CMG1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CHIEF MACHINIST''S MATE','CMM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CHIEF MOTOR MACHINIST''S MATE','CMOMM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','COOK','CK');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','COXSWAIN','COX');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','CHIEF RADIO TECHNICIAN','CRT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','COMMISSARYMAN PETTY OFFICER FIRST CLASS','CS1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','COMMISSARYMAN CHIEF PETTY OFFICER','CSC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','COMMUNICATIONS TECHNICIAN PETTY OFFICER THIRD CLASS','CT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','COMMUNICATIONS YEOMAN SEAMAN','CYNSN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','ELECTRICIAN''S MATE PETTY OFFICER SECOND CLASS','EM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','ELECTRONICS TECHNICIAN (COMMUNICATIONS) PETTY OFFICER SECOND CLASS','ETN2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','ELECTRONICS TECHNICIAN PETTY OFFICER SECOND CLASS','ET2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','ELECTRICIAN''S MATE PETTY OFFICER FIRST CLASS (SUBMARINE SERVICE)','EM1(SS)');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','ELECTRICIAN''S MATE PETTY OFFICER FIRST CLASS','EM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','ELECTRICIAN''S MATE PETTY OFFICER THIRD CLASS','EM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','ENGINEMAN PETTY OFFICER SECOND CLASS','EN2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','FIREMAN FIRST CLASS','F1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','FIREMAN SECOND CLASS','F2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','FIREMAN','FN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','PIPEFITTER PETTY OFFICER SECOND CLASS','FP2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','FIREMAN RECRUIT','FR');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','GUNNER''S MATE THIRD CLASS PETTY OFFICER','GM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','GUNNER''S MATE (MISSILES) SENIOR CHIEF PETTY OFFICER','GMCS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','GUNNER''S MATE (GUNS) PETTY OFFICER FIRST CLASS','GMG1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','GUNNER''S MATE (GUNS) PETTY OFFICER THIRD CLASS','GMG3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','HOSPITAL CORPSMAN PETTY OFFICER THIRD CLASS','HM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','HULL MAINTENANCE TECHNICIAN SENIOR CHIEF PETTY OFFICER','HTCS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','LANDSMAN','LDS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','METALSMITH FIRST CLASS PETTY OFFICER','M1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MACHINIST''S MATE SECOND CLASS PETTY OFFICER','MM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MACHINIST''S MATE FIRST CLASS PETTY OFFICER (SUBMARINE SERVICE)','MM1(SS)');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MACHINIST''S MATE FIRST CLASS PETTY OFFICER','MM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','METALSMITH PETTY OFFICER THIRD CLASS','ME3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MECHANIC PETTY OFFICER FIRST CLASS','CM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MACHINIST''S MATE THIRD CLASS PETTY OFFICER','MM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MACHINIST''S MATE (GENERAL) CHIEF PETTY OFFICER','MMLC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MOTOR MACHINIST''S MATE THIRD CLASS PETTY OFFICER','MOMM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','MACHINIST''S MATE (SHOP MACHINIST) FIRST CLASS PETTY OFFICER','MMS1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','PHOTOGRAPHER''S MATE AIRMAN','PHAN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','PHOTOGRAPHER''S MATE PETTY OFFICER FIRST CLASS','PH1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','PATTERNMAKER PETTY OFFICER SECOND CLASS','PM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','PAINTER SECOND CLASS PETTY OFFICER','PTR2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','RADIOMAN PETTY OFFICER FIRST CLASS','RM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','RADIOMAN PETTY OFFICER THIRD CLASS','RM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','RADARMAN PETTY OFFICER FIRST CLASS','RD1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','RADARMAN THIRD CLASS PETTY OFFICER','RDM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','RADIOMAN CHIEF PETTY OFFICER','RMC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','RADIOMAN SEAMAN','RMSN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SEAMAN FIRST CLASS','S1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SEAMAN SECOND CLASS','S2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SEAMAN SIGNAL COMMUNICATION','SSC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SHIPFITTER THIRD CLASS','SF3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SHIPFITTER (PIPE FITTER) PETTY OFFICER SECOND CLASS','SFP2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SHIP''S SERVICEMAN PETTY OFFICER FIRST CLASS','SH1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SHIP''S SERVICEMAN MASTER CHIEF PETTY OFFICER','SHCM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','STOREKEEPER SECOND CLASS PETTY OFFICER','SK2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SONARMAN PETTY OFFICER FIRST CLASS','SO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SOUNDMAN THIRD CLASS PETTY OFFICER','SOM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','SHIP''S SERVICEMAN (LAUNDRY MAN) SECOND CLASS PETTY OFFICER','SSML2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','TELEMAN (MAILMAN) PETTY OFFICER SECOND CLASS','TEM2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','TORPEDOMAN''S MATE PETTY OFFICER THIRD CLASS','TM3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','TORPEDOMAN''S MATE PETTY OFFICER FIRST CLASS','TM1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','WATER TENDER PETTY OFFICER SECOND CLASS','WT2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','WATER TENDER PETTY OFFICER THIRD CLASS','WT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','YEOMAN SECOND CLASS','Y2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','YEOMAN (TYPIST) PETTY OFFICER THIRD CLASS','YNT3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','YEOMAN CHIEF PETTY OFFICER','YNC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVAL RESERVE','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','PRIVATE','PVT.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','PRIVATE FIRST CLASS','PFC.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','TECHNICIAN FIFTH CLASS','T/5.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','CORPROAL','CPL.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','TECHNICIAN FOURTH CLASS','T/4.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','SERGEANT','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','TECHNICIAN THIRD CLASS','T/3.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','STAFF SERGEANT','S/SGT.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','TECHNICAL SERGEANT','T/SGT.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','FIRST SERGEANT','1ST SGT.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','MASTER SERGEANT','M/SGT.');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','FLIGHT OFFICER','FO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','WARRANT OFFICER','WO');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','CHIEF WARRANT OFFICER','W2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','SECOND LIEUTENANT','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','FIRST LIEUTENANT','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','CAPTAIN','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','MAJOR','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','LIEUTENANT COLONEL','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','COLONEL','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','BRIGADIER GENERAL','BG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','MAJOR GENERAL','MG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','LIEUTENANT GENERAL','LTG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','GENERAL','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','GENERAL OF THE ARMY','GA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Private','PV1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Private Second Class','PV2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Private First Class','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Specialist','SPC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Staff Sergeant','SSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Sergeant First Class','SFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Master Sergeant','MSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','First Sergeant','1SG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Sergeant Major','SGM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Command Sergeant Major','CSM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Sergeant Major of the Army','SMA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Warrant Officer 1','WO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Chief Warrant Officer Second Class','CW2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Chief Warrant Officer Third Class','CW3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Chief Warrant Officer Fourth Class','CW4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Chief Warrant Officer Fifth Class','CW5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','First Lieutenant','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Captain','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Lieutenant Colonel','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Brigadier General','BG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Major General','MG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','Lieutenant General','LTG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','General of the Army','GA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','General of the Armies','GAS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NATIONAL GUARD','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Private','PV1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Private Second Class','PV2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Private First Class','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Specialist','SPC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Staff Sergeant','SSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Sergeant First Class','SFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Master Sergeant','MSG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','First Sergeant','1SG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Sergeant Major','SGM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Command Sergeant Major','CSM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Sergeant Major of the Army','SMA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Warrant Officer 1','WO1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Chief Warrant Officer Second Class','CW2');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Chief Warrant Officer Third Class','CW3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Chief Warrant Officer Fourth Class','CW4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Chief Warrant Officer Fifth Class','CW5');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','First Lieutenant','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Captain','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Lieutenant Colonel','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Brigadier General','BG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Major General','MG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','Lieutenant General','LTG');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','General of the Army','GA');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','General of the Armies','GAS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Private','PVT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Musician','MUS');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Corporal','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Sergeant','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','First Sergeant','1SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Ordnance Sergeant','OSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Quartermaster Sergeant','QMSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Sergeant Major','SGM');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Second Lieutenant','2LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','First Lieutenant','1LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Captain','CPT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Major','MAJ');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Lieutenant Colonel','LTC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','Colonel','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','General','GEN');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','NONE','N/A');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNITED STATES OF AMERICA (UNION)','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','SERGEANT','SGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','STAFF SERGEANT', 'SSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','PRIVATE FIRST CLASS', 'PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','CORPORAL','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','PRIVATE','PVT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','SPECIALIST THIRD CLASS','SP3');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','COLONEL','COL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('UNKNOWN','UNKNOWN','N/A');

INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','PRIVATE','PVT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','CORPORAL','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR FORCE','CORPORAL','CPL');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','TECHNICIAN FOURTH CLASS','TEC4');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US AIR FORCE','SEAMAN FIRST CLASS','S1');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US NAVY','PRIVATE FIRST CLASS','PFC');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US ARMY AIR CORPS','TECHNICAL SERGEANT','TSGT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('CSA','LIEUTENANT','LT');
INSERT INTO RanksList (BranchName, RankName, RankAbrev) VALUES ('US MERCHANT MARINES','UNKNOWN','N/A');