/* File used to update cemeteries in accdb exported tables */

/* missing -- updated in merge (weren't dupes/changed name)
BIBB 1
Cambridge Methodist  Cemetery
GRIGSBY 2
HUNTSVILLE MEMORIAL GARDEN
ISOMS CHAPEL CEMETERY
LEBANNON
MARTIN (OLD SHOAL FORD CEMETERY
MOORESVILLE CEMEMTERY
POPLAR CREEK 1
Smithville
TEMPERENCE OAK
YARBROUGH 1
*/
UPDATE db1 SET CEMETERY='ATKINSON-HARLOW' WHERE CEMETERY='ATKINSSON-HARLOW';
UPDATE db1 SET CEMETERY='BARKER' WHERE CEMETERY='BARKER CEMETERY';
UPDATE db1 SET CEMETERY='CAMBRIDGE CHURCH CEMETERY' WHERE CEMETERY='Cambridge Methodist Cemetery';
UPDATE db1 SET CEMETERY='COLLIER 1' WHERE CEMETERY='Collier1';
UPDATE db1 SET CEMETERY='COLLIER 2' WHERE CEMETERY='Collier2';
UPDATE db1 SET CEMETERY='ELK VIEW MEMORIAL CEMETERY' WHERE CEMETERY='ELK VIEW CEMETERY';
UPDATE db1 SET CEMETERY='GATLIN' WHERE CEMETERY='GATLIN CEMETERY';
UPDATE db1 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='ISOM CHAPEL';
UPDATE db1 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='Isoms Chapel  Cemetery';
UPDATE db1 SET CEMETERY='LIMESTONE MEMORIAL GARDENS' WHERE CEMETERY='Limestone Memorial Garden';
UPDATE db1 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='Limestone Church';
UPDATE db1 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='LIMESTONE PRESBYTARIAN CHURCH CEMETERY';
UPDATE db1 SET CEMETERY='LEGG' WHERE CEMETERY='LEGGTOWN';
UPDATE db1 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='Mt Pleasant (Old scrouge Cemetery)';
UPDATE db1 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='MOUNT PLEASANT  1';
UPDATE db1 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE 1';
UPDATE db1 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE / GOOD SPRINGS';
UPDATE db1 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CEMETERY';
UPDATE db1 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CHURCH';
UPDATE db1 SET CEMETERY='RIDDLE' WHERE CEMETERY='Riddle/HENDERSON';
UPDATE db1 SET CEMETERY='SMITH' WHERE CEMETERY='Smith 1';
UPDATE db1 SET CEMETERY='SMITH' WHERE CEMETERY='Smithville';

UPDATE db2 SET CEMETERY='ATKINSON-HARLOW' WHERE CEMETERY='ATKINSSON-HARLOW';
UPDATE db2 SET CEMETERY='BARKER' WHERE CEMETERY='BARKER CEMETERY';
UPDATE db2 SET CEMETERY='CAMBRIDGE CHURCH CEMETERY' WHERE CEMETERY='Cambridge Methodist Cemetery';
UPDATE db2 SET CEMETERY='COLLIER 1' WHERE CEMETERY='Collier1';
UPDATE db2 SET CEMETERY='COLLIER 2' WHERE CEMETERY='Collier2';
UPDATE db2 SET CEMETERY='ELK VIEW MEMORIAL CEMETERY' WHERE CEMETERY='ELK VIEW CEMETERY';
UPDATE db2 SET CEMETERY='GATLIN' WHERE CEMETERY='GATLIN CEMETERY';
UPDATE db2 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='ISOM CHAPEL';
UPDATE db2 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='Isoms Chapel  Cemetery';
UPDATE db2 SET CEMETERY='LIMESTONE MEMORIAL GARDENS' WHERE CEMETERY='Limestone Memorial Garden';
UPDATE db2 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='Limestone Church';
UPDATE db2 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='LIMESTONE PRESBYTARIAN CHURCH CEMETERY';
UPDATE db2 SET CEMETERY='LEGG' WHERE CEMETERY='LEGGTOWN';
UPDATE db2 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='Mt Pleasant (Old scrouge Cemetery)';
UPDATE db2 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='MOUNT PLEASANT  1';
UPDATE db2 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE 1';
UPDATE db2 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE / GOOD SPRINGS';
UPDATE db2 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CEMETERY';
UPDATE db2 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CHURCH';
UPDATE db2 SET CEMETERY='RIDDLE' WHERE CEMETERY='Riddle/HENDERSON';
UPDATE db2 SET CEMETERY='SMITH' WHERE CEMETERY='Smith 1';
UPDATE db2 SET CEMETERY='SMITH' WHERE CEMETERY='Smithville';

UPDATE db3 SET CEMETERY='ATKINSON-HARLOW' WHERE CEMETERY='ATKINSSON-HARLOW';
UPDATE db3 SET CEMETERY='BARKER' WHERE CEMETERY='BARKER CEMETERY';
UPDATE db3 SET CEMETERY='CAMBRIDGE CHURCH CEMETERY' WHERE CEMETERY='Cambridge Methodist Cemetery';
UPDATE db3 SET CEMETERY='COLLIER 1' WHERE CEMETERY='Collier1';
UPDATE db3 SET CEMETERY='COLLIER 2' WHERE CEMETERY='Collier2';
UPDATE db3 SET CEMETERY='ELK VIEW MEMORIAL CEMETERY' WHERE CEMETERY='ELK VIEW CEMETERY';
UPDATE db3 SET CEMETERY='GATLIN' WHERE CEMETERY='GATLIN CEMETERY';
UPDATE db3 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='ISOM CHAPEL';
UPDATE db3 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='Isoms Chapel  Cemetery';
UPDATE db3 SET CEMETERY='LIMESTONE MEMORIAL GARDENS' WHERE CEMETERY='Limestone Memorial Garden';
UPDATE db3 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='Limestone Church';
UPDATE db3 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='LIMESTONE PRESBYTARIAN CHURCH CEMETERY';
UPDATE db3 SET CEMETERY='LEGG' WHERE CEMETERY='LEGGTOWN';
UPDATE db3 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='Mt Pleasant (Old scrouge Cemetery)';
UPDATE db3 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='MOUNT PLEASANT  1';
UPDATE db3 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE 1';
UPDATE db3 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE / GOOD SPRINGS';
UPDATE db3 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CEMETERY';
UPDATE db3 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CHURCH';
UPDATE db3 SET CEMETERY='RIDDLE' WHERE CEMETERY='Riddle/HENDERSON';
UPDATE db3 SET CEMETERY='SMITH' WHERE CEMETERY='Smith 1';
UPDATE db3 SET CEMETERY='SMITH' WHERE CEMETERY='Smithville';

UPDATE db4 SET CEMETERY='ATKINSON-HARLOW' WHERE CEMETERY='ATKINSSON-HARLOW';
UPDATE db4 SET CEMETERY='BARKER' WHERE CEMETERY='BARKER CEMETERY';
UPDATE db4 SET CEMETERY='CAMBRIDGE CHURCH CEMETERY' WHERE CEMETERY='Cambridge Methodist Cemetery';
UPDATE db4 SET CEMETERY='COLLIER 1' WHERE CEMETERY='Collier1';
UPDATE db4 SET CEMETERY='COLLIER 2' WHERE CEMETERY='Collier2';
UPDATE db4 SET CEMETERY='ELK VIEW MEMORIAL CEMETERY' WHERE CEMETERY='ELK VIEW CEMETERY';
UPDATE db4 SET CEMETERY='GATLIN' WHERE CEMETERY='GATLIN CEMETERY';
UPDATE db4 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='ISOM CHAPEL';
UPDATE db4 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='Isoms Chapel  Cemetery';
UPDATE db4 SET CEMETERY='LIMESTONE MEMORIAL GARDENS' WHERE CEMETERY='Limestone Memorial Garden';
UPDATE db4 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='Limestone Church';
UPDATE db4 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='LIMESTONE PRESBYTARIAN CHURCH CEMETERY';
UPDATE db4 SET CEMETERY='LEGG' WHERE CEMETERY='LEGGTOWN';
UPDATE db4 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='Mt Pleasant (Old scrouge Cemetery)';
UPDATE db4 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='MOUNT PLEASANT  1';
UPDATE db4 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE 1';
UPDATE db4 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE / GOOD SPRINGS';
UPDATE db4 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CEMETERY';
UPDATE db4 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CHURCH';
UPDATE db4 SET CEMETERY='RIDDLE' WHERE CEMETERY='Riddle/HENDERSON';
UPDATE db4 SET CEMETERY='SMITH' WHERE CEMETERY='Smith 1';
UPDATE db4 SET CEMETERY='SMITH' WHERE CEMETERY='Smithville';

UPDATE db5 SET CEMETERY='ATKINSON-HARLOW' WHERE CEMETERY='ATKINSSON-HARLOW';
UPDATE db5 SET CEMETERY='BARKER' WHERE CEMETERY='BARKER CEMETERY';
UPDATE db5 SET CEMETERY='CAMBRIDGE CHURCH CEMETERY' WHERE CEMETERY='Cambridge Methodist Cemetery';
UPDATE db5 SET CEMETERY='COLLIER 1' WHERE CEMETERY='Collier1';
UPDATE db5 SET CEMETERY='COLLIER 2' WHERE CEMETERY='Collier2';
UPDATE db5 SET CEMETERY='ELK VIEW MEMORIAL CEMETERY' WHERE CEMETERY='ELK VIEW CEMETERY';
UPDATE db5 SET CEMETERY='GATLIN' WHERE CEMETERY='GATLIN CEMETERY';
UPDATE db5 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='ISOM CHAPEL';
UPDATE db5 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='Isoms Chapel  Cemetery';
UPDATE db5 SET CEMETERY='LIMESTONE MEMORIAL GARDENS' WHERE CEMETERY='Limestone Memorial Garden';
UPDATE db5 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='Limestone Church';
UPDATE db5 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='LIMESTONE PRESBYTARIAN CHURCH CEMETERY';
UPDATE db5 SET CEMETERY='LEGG' WHERE CEMETERY='LEGGTOWN';
UPDATE db5 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='Mt Pleasant (Old scrouge Cemetery)';
UPDATE db5 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='MOUNT PLEASANT  1';
UPDATE db5 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE 1';
UPDATE db5 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE / GOOD SPRINGS';
UPDATE db5 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CEMETERY';
UPDATE db5 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CHURCH';
UPDATE db5 SET CEMETERY='RIDDLE' WHERE CEMETERY='Riddle/HENDERSON';
UPDATE db5 SET CEMETERY='SMITH' WHERE CEMETERY='Smith 1';
UPDATE db6 SET CEMETERY='SMITH' WHERE CEMETERY='Smithville';

UPDATE db6 SET CEMETERY='ATKINSON-HARLOW' WHERE CEMETERY='ATKINSSON-HARLOW';
UPDATE db6 SET CEMETERY='BARKER' WHERE CEMETERY='BARKER CEMETERY';
UPDATE db6 SET CEMETERY='CAMBRIDGE CHURCH CEMETERY' WHERE CEMETERY='Cambridge Methodist Cemetery';
UPDATE db6 SET CEMETERY='COLLIER 1' WHERE CEMETERY='Collier1';
UPDATE db6 SET CEMETERY='COLLIER 2' WHERE CEMETERY='Collier2';
UPDATE db6 SET CEMETERY='ELK VIEW MEMORIAL CEMETERY' WHERE CEMETERY='ELK VIEW CEMETERY';
UPDATE db6 SET CEMETERY='GATLIN' WHERE CEMETERY='GATLIN CEMETERY';
UPDATE db6 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='ISOM CHAPEL';
UPDATE db6 SET CEMETERY='ISOMS CHAPEL CEMETERY' WHERE CEMETERY='Isoms Chapel  Cemetery';
UPDATE db6 SET CEMETERY='LIMESTONE MEMORIAL GARDENS' WHERE CEMETERY='Limestone Memorial Garden';
UPDATE db6 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='Limestone Church';
UPDATE db6 SET CEMETERY='LIMESTONE PRESBYTERIAN CHURCH CEMETERY' WHERE CEMETERY='LIMESTONE PRESBYTARIAN CHURCH CEMETERY';
UPDATE db6 SET CEMETERY='LEGG' WHERE CEMETERY='LEGGTOWN';
UPDATE db6 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='Mt Pleasant (Old scrouge Cemetery)';
UPDATE db6 SET CEMETERY='MOUNT PLEASANT' WHERE CEMETERY='MOUNT PLEASANT  1';
UPDATE db6 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE 1';
UPDATE db6 SET CEMETERY='OAK GROVE' WHERE CEMETERY='OAK GROVE / GOOD SPRINGS';
UPDATE db6 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CEMETERY';
UPDATE db6 SET CEMETERY='PETTUSVILLE CHURCH CEMETERY' WHERE CEMETERY='PETTUSVILLE CHURCH';
UPDATE db6 SET CEMETERY='RIDDLE' WHERE CEMETERY='Riddle/HENDERSON';
UPDATE db6 SET CEMETERY='SMITH' WHERE CEMETERY='Smith 1';
UPDATE db6 SET CEMETERY='SMITH' WHERE CEMETERY='Smithville';
